import collections
import random
from typing import List
import ranjg
from ranjg.util.listutil import fix_length
from ranjg.util.nonesafe import dfor
from .validate.schema import validate_schema
from .error import SchemaConflictError

# 配列の要素の値の生成に使用するスキーマのデフォルト値。
# items に指定がない場合に使用する。
__default_items_schema = {
    "type": "number",
    "minimum": 0,
    "maximum": 0,
}


def genlist(schema: dict, schema_is_validated: bool = False) -> list:
    """Generate a random list according to the JSON schema.

    This function ignores ``schema.type`` because it is basically designed to be called by ``ranjg.gen``.

    Args:
        schema: JSON schema object.
        schema_is_validated: Whether the schema is already validated or not.

    Returns:
        Generated list.
    """

    # スキーマの不正判定
    if not schema_is_validated:
        validate_schema(schema)

    # 生成するリスト
    result = []

    # 生成する list の大きさの範囲
    [min_items, max_items] = __get_range_of_length(schema)

    # 生成する list の大きさ
    item_count = random.randint(min_items, max_items)

    # 各要素のスキーマ
    item_schema_list = __get_items_schema_list(schema, item_count)

    # 要素を1つずつ生成
    for item_schema in item_schema_list:
        generated_item = ranjg.gen(item_schema, schema_is_validated=True)
        result.append(generated_item)

    return result


def __schema_is_tuple_validation(schema: dict) -> bool:
    """Determines if the schema is for a tuple validation or not.

    Args:
        schema: JSON schema object for list values.

    Returns:
        True if the schema is for a tuple validation, otherwise False.
    """

    items = schema.get("items")
    return isinstance(items, collections.abc.Sequence)


def __get_range_of_length(schema: dict) -> [int, int]:
    """Determine the range of the size of the list to be generated with the schema.

    Even if they are not specified in the schema, two positive integer values are returned instead of None.
    If only one of them is None (null), then an integer value consistent with the other is returned instead.
    If both are None (null), the default values are returned.

    Args:
        schema: JSON schema object for list values.

    Returns:
        The minimum and maximum size of the list to be generated.
    """

    min_items: int = schema.get("minItems")
    max_items: int = schema.get("maxItems")

    # schema がタプル指定である場合
    if __schema_is_tuple_validation(schema):
        items = list(schema.get("items"))
        additional_items = schema.get("additionalItems")

        if additional_items is False and len(items) < dfor(min_items, len(items)):
            raise SchemaConflictError(
                "In tuple validation, when \"additionalItems\" is false, \"minItems\" must be less than or equal to "
                "size of \"items\".")

    if min_items is None:
        if max_items is None:
            min_items = 1
        else:
            min_items = min(1, max_items)

    if max_items is None:
        if min_items is None:
            max_items = 5
        else:
            max_items = max(5, min_items)

    return [min_items, max_items]


def __get_items_schema_list(schema: dict, item_count: int) -> List[dict]:
    """Returns a list of schemas for generating each element of the list generated by ``genlist``.

    If the schema is for tuple validation, this function returns a list similar to ``schema.items``.
    However, if the size of items is less than ``item_count``, ``schema.additionalItems`` is used for the missing part.

    If schema is for list validation, it returns a list containing ``item_count`` of ``items``.

    Args:
        schema: JSON schema object for list values.
        item_count: The length of the list to generate with ``genlist``.

    Returns:
        A list consisting of the schemas used to generate each element.
    """

    # タプル指定である場合
    if __schema_is_tuple_validation(schema):
        additional_items = schema.get('additionalItems')
        if additional_items is None or isinstance(additional_items, bool):
            additional_items = __default_items_schema

        return fix_length(schema["items"], item_count, padding_item=additional_items)
    # リスト指定である場合
    else:
        return item_count * [schema.get("items", __default_items_schema)]
